### ISSUE TITLE
Trivy finds critical AWS access key ID vulnerability in moto

### ISSUE THREAD

**Issue by fredrikaverpil** [getmoto/moto#5975]
Hey 👋 

I just want to give you a headsup on that when you run [trivy](https://www.aquasec.com/products/trivy/) on a docker image (`python:3.10` image) with moto installed into a venv, you will get a critical alert, like this:

```
/redacted/lib/python3.10/site-packages/moto/sts/models.py (secrets)
===================================================================
Total: 1 (HIGH: 0, CRITICAL: 1)

CRITICAL: AWS (aws-access-key-id)
════════════════════════════════════════
AWS Access Key ID
────────────────────────────────────────
 /redacted/lib/python3.10/site-packages/moto/sts/models.py:174
────────────────────────────────────────
 172   
 173           # Default values in case the request does not use valid credentials generated by moto
 174 [         user_id = "********************"
 175           arn = f"arn:aws:sts::{self.account_id}:user/moto"
────────────────────────────────────────
```

I'm going to try and figure out a way to ignore this warning, but it would maybe be of interest to you to add docs around this or maybe even prevent it from happening in the first place?

I'm using the GitHub action and I'm running it like this:

```yml
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - (building the docker image here)

      - name: Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "my-image-name:${{ github.sha }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
```

**Comment by bblommers** [comment]
Hi @fredrikaverpil! As Moto is a test library, I would consider any security alert a false positive. Any credentials that we expose are mocked, so that is not a problem.

If you find workaround and can share that here, that would be useful for other people with the same problem!

**Comment by fredrikaverpil** [comment]
I agree 100%.

Feel free to close this issue and I can update later with a comment on suggested mitigation.

**Comment by fredrikaverpil** [comment]
I would just like to add to this thread the reason for why I like to run vulnerability checks on developer dependencies such as moto; any testing library or developer dependency could in theory attempt to steal data from the production code or the CI environment. Therefore we include developer tools and libraries in the vulnerability scan.

**Comment by fredrikaverpil** [comment]
I've found two ways you can mitigate this.

1. Add a `trivy-secret.yaml` file with something like the following contents:

```yml
allow-rules:
  - id: aws-access-key-id
    description: skip mocked AWS key, provided by moto
    regex: AKIAIOSFODNN7EXAMPLE
    path: /opt/venv/lib/python3.10/site-packages/moto/sts/models.py
```

3. Skip checking the "offending file" in question with `skip-files`:

```yml
      - name: Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "my-image-name:${{ github.sha }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
          skip-files: /opt/venv/lib/python3.10/site-packages/moto/sts/models.py

```
