### ISSUE TITLE
Configuring the stand-alone-server to allow boto3 clients to create queues

### ISSUE THREAD

**Issue by nicholasd-ff** [getmoto/moto#6361]
Hi moto people!

I'm having trouble configuring the stand-alone-server docker container to allow me to create sqs queues. I'm sure this used to work, but I've back-tracked as far as moto `3.1.18` and as new as `latest` and also tried various  boto3 version all the way back to march and I don't seem to be able to create a queue:
```
moto-standalone-sqs-test-mock-aws-api-1  | WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
moto-standalone-sqs-test-mock-aws-api-1  |  * Running on all addresses (0.0.0.0)
moto-standalone-sqs-test-mock-aws-api-1  |  * Running on http://127.0.0.1:5000
moto-standalone-sqs-test-mock-aws-api-1  |  * Running on http://172.28.0.2:5000
moto-standalone-sqs-test-mock-aws-api-1  | Press CTRL+C to quit
moto-standalone-sqs-test-moto-init-1     | AWS_SESSION_TOKEN=testing
moto-standalone-sqs-test-moto-init-1     | AWS_REGION=us-east-1
moto-standalone-sqs-test-moto-init-1     | AWS_ENDPOINT_URL=http://test-mock-aws-api:5000
moto-standalone-sqs-test-moto-init-1     | AWS_ACCESS_KEY_ID=testing
moto-standalone-sqs-test-moto-init-1     | AWS_SECRET_ACCESS_KEY=testing
moto-standalone-sqs-test-moto-init-1     | AWS_SECURITY_TOKEN=testing
moto-standalone-sqs-test-moto-init-1     | Traceback (most recent call last):
moto-standalone-sqs-test-moto-init-1     |   File "/app/./entrypoint.py", line 14, in <module>
moto-standalone-sqs-test-moto-init-1     |     sqs.create_queue(QueueName="regular_q")
moto-standalone-sqs-test-moto-init-1     |   File "/usr/local/lib/python3.11/site-packages/boto3/resources/factory.py", line 580, in do_action
moto-standalone-sqs-test-moto-init-1     |     response = action(self, *args, **kwargs)
moto-standalone-sqs-test-moto-init-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
moto-standalone-sqs-test-moto-init-1     |   File "/usr/local/lib/python3.11/site-packages/boto3/resources/action.py", line 88, in __call__
moto-standalone-sqs-test-moto-init-1     |     response = getattr(parent.meta.client, operation_name)(*args, **params)
moto-standalone-sqs-test-moto-init-1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
moto-standalone-sqs-test-moto-init-1     |   File "/usr/local/lib/python3.11/site-packages/botocore/client.py", line 530, in _api_call
moto-standalone-sqs-test-moto-init-1     |     return self._make_api_call(operation_name, kwargs)
moto-standalone-sqs-test-moto-init-1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
moto-standalone-sqs-test-moto-init-1     |   File "/usr/local/lib/python3.11/site-packages/botocore/client.py", line 964, in _make_api_call
moto-standalone-sqs-test-moto-init-1     |     raise error_class(parsed_response, operation_name)
moto-standalone-sqs-test-moto-init-1     | botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the CreateQueue operation: The security token included in the request is invalid.
moto-standalone-sqs-test-moto-init-1 exited with code 1
```

Things I've tried:
 * Setting various combinations of the `AWS_*` environment variables
 * Setting identical environment variables in both the stand-alone container and the 
I've attached a minimal example in [moto-standalone-sqs.zip](https://github.com/getmoto/moto/files/11634188/moto-standalone-sqs.zip), and reproduced the code below, just in case my mistake is so obvious it saves someone having to download and extract the zip.

`.env`:
```
MOTO_VER=4.1.10
BOTO_VER=1.26.145
```
`docker-compose.yml`:
```yaml
x-aws-env: &aws-env
  AWS_ENDPOINT_URL: "http://test-mock-aws-api:5000"
  AWS_ACCESS_KEY_ID: "testing"
  AWS_SECRET_ACCESS_KEY: "testing"
  AWS_SECURITY_TOKEN: "testing"
  AWS_SESSION_TOKEN: "testing"
  AWS_REGION: "us-east-1"
services:
  test-mock-aws-api:
    image: motoserver/moto:$MOTO_VER
    ports:
      - "5000"
    environment:
      <<: [ *aws-env ]
  test-moto-init:
    depends_on:
      test-mock-aws-api:
        condition: service_started
    build: 
      context: .
      args:
        MOTO_VER: $MOTO_VER
        BOTO_VER: $BOTO_VER
    environment:
      <<: [ *aws-env ]
```
`Dockerfile`:
```dockerfile
FROM python:3.11
ARG MOTO_VER
ARG BOTO_VER
WORKDIR /app
RUN pip install moto==${MOTO_VER} boto3==${BOTO_VER}
COPY entrypoint.py entrypoint.py
ENTRYPOINT [ "./entrypoint.py" ]
```
`entrypoint.py`:
```python
#!/usr/bin/env python3
import os
import sys
import boto3

for k,v in os.environ.items():
    if k.startswith("AWS_"):
        print(f"{k}={v}", flush=True, file=sys.stderr)
sqs = boto3.resource('sqs', region_name=os.environ["AWS_REGION"])
sqs.create_queue(QueueName="regular_q")
sqs.create_queue(QueueName="fifo_q.fifo", Attributes={'FifoQueue': 'true'})
```
