### ISSUE TITLE
How can data around Cognito be persisted when using docker?

### ISSUE THREAD

**Issue by sion908** [getmoto/moto#7783]
Moto always helps me.
However, when I stop Docker, the data is lost.
Is there a way to make it persistent?
If there is, it would be helpful if it was written in the documentation.
I especially use services related to cognito.

```
  mock-aws-local:
    image: motoserver/moto:latest
    environment:
      MOTO_PORT: 4000
    ports:
      - ${AWS_LOCAL_PORT:-4000}:4000
```
