### ISSUE TITLE
How to setup bucket on docker server startup?

### ISSUE THREAD

**Issue by mglowinski93** [getmoto/moto#8689]
Hi,
I've `docker compose` configuration like this:

```aws-mock:
    image: "motoserver/moto:5.1.1"
    restart: "no"
    container_name: management-application-template-aws-mock-development
    networks:
      management-application-template:
    ports:
      - "3000:3000"
    volumes:
      - "management-application-template-aws-mock-volume:/data"
    environment:
      MOTO_PORT: 3000
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:3000/ || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
```

What is recommended way to setup required configuration e.g. creating a bucket on startup?

**Comment by bblommers** [comment]
Hi @mglowinski93, I wouldn't say there is a _recommended_ way - just because there are so many different use cases.

If you have a complicated setup, you could use the Recorder-feature to easily record/store the setup once, and load it as you see fit. See the docs here: https://docs.getmoto.org/en/latest/docs/configuration/recorder/index.html

When using DockerCompose, I'd suggest looking into using another service with the sole responsibility of loading the setup. Something like:
```
motosetup:
    image: some_image_that_supports_curl
    depends_on:
      - moto
    restart: "no"
    entrypoint: [ "bash", "-c", "curl http://localhost:5000/moto-api/recorder/replay-recording --data-binary ..."]
```
I haven't tested it, but that seems like it should work.
